In [1]:
import cv2
import numpy as np

ModuleNotFoundError: No module named 'cv2'

In [2]:
image = np.array([[1, 0, 2, 1, 0],
				  [0, 2, 3, 0, 1],
				  [1, 0, 1, 1, 2],
				  [0, 2, 2, 0, 3],
				  [0, 4, 1, 2, 0]])

In [4]:
image = image / 5.0

In [7]:
image

array([[0.2, 0. , 0.4, 0.2, 0. ],
       [0. , 0.4, 0.6, 0. , 0.2],
       [0.2, 0. , 0.2, 0.2, 0.4],
       [0. , 0.4, 0.4, 0. , 0.6],
       [0. , 0.8, 0.2, 0.4, 0. ]])

### Create kernel or Feature Detection or Filter or Mask

In [10]:
kernel1 = np.array([[-1, 0, 1],
					[-1, 0, 1],
					[-1, 0, 1]])

### Convolude

In [11]:
im2 = cv2.filter2D(src=image, ddepth=-1, kernel=kernel1)

In [12]:
im2

array([[ 0. ,  1.4, -0.6, -1.2,  0. ],
       [ 0. ,  0.8,  0. , -0.6,  0. ],
       [ 0. ,  1. , -0.6,  0. ,  0. ],
       [ 0. ,  0.6, -0.6,  0.2,  0. ],
       [ 0. ,  1. , -1.2,  0.2,  0. ]])

In [13]:
im2_int = (im2 * 5).astype('int')

In [14]:
im2_int

array([[ 0,  7, -3, -6,  0],
       [ 0,  4,  0, -3,  0],
       [ 0,  5, -3,  0,  0],
       [ 0,  3, -3,  0,  0],
       [ 0,  5, -6,  0,  0]])