## Regression Using Artificial Neural Network

### Importing The Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

### Part 1 - Data Prepocessing

#### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

#### Splitting the dataset into the test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Part 2 - Building the ANN

#### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

#### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

### Part 3 - Training the ANN

#### Compiling the ANN

In [11]:
ann.compile(optimizer='adam', loss='mean_squared_error')

#### Training the ANN model on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size= 32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 804us/step - loss: 44561.8672
Epoch 2/100
240/240 [==============================] - 0s 728us/step - loss: 510.6857
Epoch 3/100
240/240 [==============================] - 0s 779us/step - loss: 474.3326
Epoch 4/100
240/240 [==============================] - 0s 792us/step - loss: 460.9272
Epoch 5/100
240/240 [==============================] - 0s 757us/step - loss: 444.6541 0s - loss: 437.0
Epoch 6/100
240/240 [==============================] - 0s 766us/step - loss: 426.2880
Epoch 7/100
240/240 [==============================] - 0s 799us/step - loss: 406.5146
Epoch 8/100
240/240 [==============================] - 0s 1000us/step - loss: 385.2724
Epoch 9/100
240/240 [==============================] - 0s 795us/step - loss: 362.2424
Epoch 10/100
240/240 [==============================] - 0s 791us/step - loss: 338.5001
Epoch 11/100
240/240 [==============================] - 0s 778us/step - loss: 314.2629
Epoch 12/100
240/240 [==========

#### Predicting the results of the test set

In [13]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))	

[[432.09 431.23]
 [463.23 460.01]
 [466.75 461.14]
 ...
 [473.98 473.26]
 [440.71 438.  ]
 [459.96 463.28]]


In [14]:
from sklearn.metrics import r2_score
print(r2_score(y_pred, y_test))

0.9087396407706865
