## Regression Using Artificial Neural Network

### Importing The Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

### Part 1 - Data Prepocessing

#### Importing the dataset

In [4]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [6]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

#### Splitting the dataset into the test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Part 2 - Building the ANN

#### Initializing the ANN

In [11]:
ann = tf.keras.models.Sequential()

#### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1))

### Part 3 - Training the ANN

#### Compiling the ANN

In [15]:
ann.compile(optimizer='adam', loss='mean_squared_error')

#### Training the ANN model on the Training set

In [16]:
ann.fit(X_train, y_train, batch_size= 32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 2100.5393
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 185.2717
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 172.2544
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 157.2300
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 141.5777
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 125.6470
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 110.3036
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 96.1797
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 83.3157
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 71.8971
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 61.4299
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 5

#### Predicting the results of the test set

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))	

[[432.35 431.23]
 [463.4  460.01]
 [466.89 461.14]
 ...
 [474.14 473.26]
 [440.85 438.  ]
 [460.09 463.28]]
