# Quick Pandas-numpy tutorial

### import dataset 

click [https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv](https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv)

### Import Libaries

In [103]:
import numpy as np
import pandas as pd

### basic numpy

In [2]:
[1, 2, 3] + [10, 10, 10]
# concatinate

[1, 2, 3, 10, 10, 10]

In [3]:
[1, 2, 3]* 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
np.array([1, 2, 3]) + np.array([10, 10, 10 ]) # add with index

array([11, 12, 13])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
np.arange(5,10) # start , stop -1 

array([5, 6, 7, 8, 9])

In [7]:
np.arange(5,10,2) # start , stop -1, step

array([5, 7, 9])

In [ ]:
np.random.rand(5)

array([0.23145269, 0.05308467, 0.97849332, 0.29440131, 0.83630067])

In [82]:
np.random.randint(0,10,5) 

array([5, 8, 8, 1, 3])

In [83]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [84]:
x = np.arange(0,5)

In [85]:
x

array([0, 1, 2, 3, 4])

In [86]:
x.sum()

10

In [88]:
np.sum(x)

10

In [89]:
x.mean()

2.0

In [90]:
x.min()

0

In [91]:
x.max()

4

In [92]:
x.std()

1.4142135623730951

In [93]:
x

array([0, 1, 2, 3, 4])

In [96]:
x[2]

2

In [97]:
x[0:3] # start , end -1

array([0, 1, 2])

In [98]:
x[:3]

array([0, 1, 2])

In [100]:
x[3:]

array([3, 4])

In [101]:
x[-1]

4

In [102]:
x[-2]

3

### Pandas Series & Pandas Datafram

In [104]:
s1 = pd.Series([0, 10, 20])

In [105]:
s1

0     0
1    10
2    20
dtype: int64

In [106]:
type(s1)

pandas.core.series.Series

In [108]:
np.sum(s1) # np.array & pd.Series can use together

30

In [109]:
s1.mean()

10.0

In [110]:
s1.max()

20

In [111]:
s1.sum()

30

In [112]:
s2 = pd.Series(["A","B","C"])

In [113]:
s2

0    A
1    B
2    C
dtype: object

In [114]:
df = pd.DataFrame({"name":s2, "working_year": s1})

In [115]:
df

name  working_year
0    A             0
1    B            10
2    C            20

In [116]:
type(df)

pandas.core.frame.DataFrame

In [117]:
type(s1)

pandas.core.series.Series

In [121]:
df["name"]

0    A
1    B
2    C
Name: name, dtype: object

In [122]:
df[["name"]]

name
0    A
1    B
2    C

In [124]:
type(df["name"])

pandas.core.series.Series

In [125]:
type(df[["name"]])

pandas.core.frame.DataFrame

In [120]:
type(df["working_year"])

pandas.core.series.Series

### Read CSV into a Pandas Dataframe

In [126]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [127]:
df = pd.read_csv(CSV_PATH)

In [128]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [130]:
df.head(3) # dump 5 by defualt

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi

In [131]:
df.tail()

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

### Column Selection

In [132]:
df['name']

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [133]:
df[["name"]]

name
0      Anda
1    Bordin
2  Chantana
3   Donlaya
4   Ekkasit
5    Fundee
6   Gitiwit
7     Harit

In [136]:
df[["name", "gender", "age"]]

name  gender  age
0      Anda  female   39
1    Bordin    male   25
2  Chantana  female   29
3   Donlaya  female   39
4   Ekkasit    male   37
5    Fundee  female   35
6   Gitiwit    male   26
7     Harit    male   32

### Row Selection

In [137]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary             48700.0
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [138]:
type(df.loc[1])

pandas.core.series.Series

In [139]:
df.loc[[1]]

eid    name gender department  age   salary  working_years birth_place
1  E012  Bordin   male  developer   25  48700.0              2      Phuket

In [140]:
type(df.loc[[1]])


pandas.core.frame.DataFrame

In [141]:
df.loc[[1, 2, 3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

### Row & Column Selection

In [145]:
df.loc[1, ["name", 'age']] # [ row, [ column ]]

name    Bordin
age         25
Name: 1, dtype: object

In [146]:
type(df.loc[1, ["name", 'age']])

pandas.core.series.Series

In [147]:
df.loc[[1], ['name', 'age']]

name  age
1  Bordin   25

In [148]:
type(df.loc[[1], ['name', 'age']])

pandas.core.frame.DataFrame

In [149]:
df.loc[[1, 2, 3], ['name', 'age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [151]:
df[['name', 'age']].loc[[1, 2, 3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [152]:
df.loc[[1, 2, 3]]['name']

1      Bordin
2    Chantana
3     Donlaya
Name: name, dtype: object

In [153]:
type(df.loc[[1, 2, 3]]['name'])

pandas.core.series.Series

In [155]:
df.loc[[1, 2, 3]][['name', 'age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

### Value Modification

In [159]:
df[["name", "working_years"]]

name  working_years
0      Anda              4
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [160]:
df.loc[0, "working_years"] = 77

In [162]:
df[['name', 'working_years']]

name  working_years
0      Anda             77
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [163]:
df.loc[[1, 2] ,'working_years'] = 9999

In [164]:
df[['name', 'working_years']]

name  working_years
0      Anda             77
1    Bordin           9999
2  Chantana           9999
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [165]:
df.loc[[1, 2], ['name', 'working_years']] = 'MODIFIED'

In [166]:
df[['name', 'working_years']]

name working_years
0      Anda            77
1  MODIFIED      MODIFIED
2  MODIFIED      MODIFIED
3   Donlaya             8
4   Ekkasit             7
5    Fundee             3
6   Gitiwit             2
7     Harit             5

In [167]:
df

eid      name  gender department  age   salary working_years birth_place
0  E011      Anda  female  developer   39  64200.0            77     Bangkok
1  E012  MODIFIED    male  developer   25  48700.0      MODIFIED      Phuket
2  E013  MODIFIED  female  developer   29  45500.0      MODIFIED    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0             8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0             7  Suphanburi
5  E016    Fundee  female    support   35  56600.0             3      Phuket
6  E017   Gitiwit    male    support   26  42400.0             2  Suphanburi
7  E018     Harit    male     devops   32  67700.0             5     Bangkok

### Reload Dataframe

In [169]:
df = pd.read_csv(CSV_PATH)

In [170]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [171]:
df.set_index('eid')

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [172]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [173]:
df.set_index('eid', inplace=True)

In [174]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

### Row & Column Selection 2 

In [175]:
df.loc[["E011","E012"], ['name','salary']]

name   salary
eid                  
E011    Anda  64200.0
E012  Bordin  48700.0

In [196]:
df.iloc[0]

eid                   E011
name                  Anda
gender              female
department       developer
age                     39
salary             64200.0
working_years            4
birth_place        Bangkok
Name: 0, dtype: object

In [182]:
df.iloc[[0]]

eid  name  gender department  age   salary  working_years birth_place
0  E011  Anda  female  developer   39  64200.0              4     Bangkok

In [183]:
df.iloc[[0,1]]

eid    name  gender department  age   salary  working_years birth_place
0  E011    Anda  female  developer   39  64200.0              4     Bangkok
1  E012  Bordin    male  developer   25  48700.0              2      Phuket

In [185]:
df.iloc[[0, 1]]['name']

0      Anda
1    Bordin
Name: name, dtype: object

In [207]:
type(df.iloc[[0, 1]]['name'])

pandas.core.series.Series

In [208]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [200]:
df.iloc[[0, 1]][['name', 'gender']]

name  gender
0    Anda  female
1  Bordin    male

### Reset Index

In [188]:
df.reset_index(inplace=True)

In [189]:
df

index   eid      name  gender department  age   salary  working_years  \
0      0  E011      Anda  female  developer   39  64200.0              4   
1      1  E012    Bordin    male  developer   25  48700.0              2   
2      2  E013  Chantana  female  developer   29  45500.0              3   
3      3  E014   Donlaya  female  marketing   39  72600.0              8   
4      4  E015   Ekkasit    male  marketing   37  80500.0              7   
5      5  E016    Fundee  female    support   35  56600.0              3   
6      6  E017   Gitiwit    male    support   26  42400.0              2   
7      7  E018     Harit    male     devops   32  67700.0              5   

  birth_place  
0     Bangkok  
1      Phuket  
2    Chonburi  
3    Chonburi  
4  Suphanburi  
5      Phuket  
6  Suphanburi  
7     Bangkok

### Reload Dataframe

In [190]:
df = pd.read_csv(CSV_PATH)


In [191]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

### Range Selection

In [192]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [193]:
df.loc[:4]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [194]:
df.loc[1:3, ['name','age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [212]:
df.loc[1:3][['name']]

name
1    Bordin
2  Chantana
3   Donlaya

In [214]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [215]:

df.iloc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

In [217]:
df.iloc[1:4][['name','age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

### Condition Selection

In [218]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [219]:
df[['working_years']]

working_years
0              4
1              2
2              3
3              8
4              7
5              3
6              2
7              5

In [221]:
df['working_years']

0    4
1    2
2    3
3    8
4    7
5    3
6    2
7    5
Name: working_years, dtype: int64

In [222]:
df['working_years'] > 3 # Return Boolean

0     True
1    False
2    False
3     True
4     True
5    False
6    False
7     True
Name: working_years, dtype: bool

In [223]:
df[ df['working_years'] > 3]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [226]:
df[ df['working_years'] > 3][['name','working_years','salary']]

name  working_years   salary
0     Anda              4  64200.0
3  Donlaya              8  72600.0
4  Ekkasit              7  80500.0
7    Harit              5  67700.0

In [229]:
df[ (df["working_years"]>3) & (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [231]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [233]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].iloc[[3]]

eid   name gender department  age   salary  working_years birth_place
7  E018  Harit   male     devops   32  67700.0              5     Bangkok

In [234]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].loc[[3]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi