# Quick Pandas-numpy tutorial

### import dataset 

click [https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv](https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv)

### Import Libaries

In [2]:
import numpy as np
import pandas as pd

### basic numpy

In [3]:
[1, 2, 3] + [10, 10, 10]
# concatinate

[1, 2, 3, 10, 10, 10]

In [4]:
[1, 2, 3]* 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
np.array([1, 2, 3]) + np.array([10, 10, 10 ]) # add with index

array([11, 12, 13])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(5,10) # start , stop -1 

array([5, 6, 7, 8, 9])

In [8]:
np.arange(5,10,2) # start , stop -1, step

array([5, 7, 9])

In [9]:
np.random.rand(5)

array([0.47669096, 0.17496293, 0.82285183, 0.00246273, 0.15274663])

In [10]:
np.random.randint(0,10,5) 

array([2, 4, 2, 0, 6])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
x = np.arange(0,5)

In [13]:
x

array([0, 1, 2, 3, 4])

In [14]:
x.sum()

10

In [15]:
np.sum(x)

10

In [16]:
x.mean()

2.0

In [17]:
x.min()

0

In [18]:
x.max()

4

In [19]:
x.std()

1.4142135623730951

In [20]:
x

array([0, 1, 2, 3, 4])

In [21]:
x[2]

2

In [22]:
x[0:3] # start , end -1

array([0, 1, 2])

In [23]:
x[:3]

array([0, 1, 2])

In [24]:
x[3:]

array([3, 4])

In [25]:
x[-1]

4

In [26]:
x[-2]

3

### Pandas Series & Pandas Datafram

In [27]:
s1 = pd.Series([0, 10, 20])

In [28]:
s1

0     0
1    10
2    20
dtype: int64

In [29]:
type(s1)

pandas.core.series.Series

In [30]:
np.sum(s1) # np.array & pd.Series can use together

30

In [31]:
s1.mean()

10.0

In [32]:
s1.max()

20

In [33]:
s1.sum()

30

In [34]:
s2 = pd.Series(["A","B","C"])

In [35]:
s2

0    A
1    B
2    C
dtype: object

In [36]:
df = pd.DataFrame({"name":s2, "working_year": s1})

In [37]:
df

name  working_year
0    A             0
1    B            10
2    C            20

In [38]:
type(df)

pandas.core.frame.DataFrame

In [39]:
type(s1)

pandas.core.series.Series

In [40]:
df["name"]

0    A
1    B
2    C
Name: name, dtype: object

In [41]:
df[["name"]]

name
0    A
1    B
2    C

In [42]:
type(df["name"])

pandas.core.series.Series

In [43]:
type(df[["name"]])

pandas.core.frame.DataFrame

In [44]:
type(df["working_year"])

pandas.core.series.Series

### Read CSV into a Pandas Dataframe

In [45]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [46]:
df = pd.read_csv(CSV_PATH)

In [47]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [48]:
df.head(3) # dump 5 by defualt

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi

In [49]:
df.tail()

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

### Column Selection

In [50]:
df['name']

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [51]:
df[["name"]]

name
0      Anda
1    Bordin
2  Chantana
3   Donlaya
4   Ekkasit
5    Fundee
6   Gitiwit
7     Harit

In [52]:
df[["name", "gender", "age"]]

name  gender  age
0      Anda  female   39
1    Bordin    male   25
2  Chantana  female   29
3   Donlaya  female   39
4   Ekkasit    male   37
5    Fundee  female   35
6   Gitiwit    male   26
7     Harit    male   32

### Row Selection

In [53]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary             48700.0
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [54]:
type(df.loc[1])

pandas.core.series.Series

In [55]:
df.loc[[1]]

eid    name gender department  age   salary  working_years birth_place
1  E012  Bordin   male  developer   25  48700.0              2      Phuket

In [56]:
type(df.loc[[1]])


pandas.core.frame.DataFrame

In [57]:
df.loc[[1, 2, 3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

### Row & Column Selection

In [58]:
df.loc[1, ["name", 'age']] # [ row, [ column ]]

name    Bordin
age         25
Name: 1, dtype: object

In [59]:
type(df.loc[1, ["name", 'age']])

pandas.core.series.Series

In [60]:
df.loc[[1], ['name', 'age']]

name  age
1  Bordin   25

In [61]:
type(df.loc[[1], ['name', 'age']])

pandas.core.frame.DataFrame

In [62]:
df.loc[[1, 2, 3], ['name', 'age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [63]:
df[['name', 'age']].loc[[1, 2, 3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [64]:
df.loc[[1, 2, 3]]['name']

1      Bordin
2    Chantana
3     Donlaya
Name: name, dtype: object

In [65]:
type(df.loc[[1, 2, 3]]['name'])

pandas.core.series.Series

In [66]:
df.loc[[1, 2, 3]][['name', 'age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

### Value Modification

In [67]:
df[["name", "working_years"]]

name  working_years
0      Anda              4
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [68]:
df.loc[0, "working_years"] = 77

In [69]:
df[['name', 'working_years']]

name  working_years
0      Anda             77
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [70]:
df.loc[[1, 2] ,'working_years'] = 9999

In [71]:
df[['name', 'working_years']]

name  working_years
0      Anda             77
1    Bordin           9999
2  Chantana           9999
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [72]:
df.loc[[1, 2], ['name', 'working_years']] = 'MODIFIED'

In [73]:
df[['name', 'working_years']]

name working_years
0      Anda            77
1  MODIFIED      MODIFIED
2  MODIFIED      MODIFIED
3   Donlaya             8
4   Ekkasit             7
5    Fundee             3
6   Gitiwit             2
7     Harit             5

In [74]:
df

eid      name  gender department  age   salary working_years birth_place
0  E011      Anda  female  developer   39  64200.0            77     Bangkok
1  E012  MODIFIED    male  developer   25  48700.0      MODIFIED      Phuket
2  E013  MODIFIED  female  developer   29  45500.0      MODIFIED    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0             8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0             7  Suphanburi
5  E016    Fundee  female    support   35  56600.0             3      Phuket
6  E017   Gitiwit    male    support   26  42400.0             2  Suphanburi
7  E018     Harit    male     devops   32  67700.0             5     Bangkok

### Reload Dataframe

In [75]:
df = pd.read_csv(CSV_PATH)

In [76]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [77]:
df.set_index('eid')

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [78]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [79]:
df.set_index('eid', inplace=True)

In [80]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

### Row & Column Selection 2 

In [81]:
df.loc[["E011","E012"], ['name','salary']]

name   salary
eid                  
E011    Anda  64200.0
E012  Bordin  48700.0

In [82]:
df.iloc[0]

name                  Anda
gender              female
department       developer
age                     39
salary             64200.0
working_years            4
birth_place        Bangkok
Name: E011, dtype: object

In [83]:
df.iloc[[0]]

name  gender department  age   salary  working_years birth_place
eid                                                                   
E011  Anda  female  developer   39  64200.0              4     Bangkok

In [84]:
df.iloc[[0,1]]

name  gender department  age   salary  working_years birth_place
eid                                                                     
E011    Anda  female  developer   39  64200.0              4     Bangkok
E012  Bordin    male  developer   25  48700.0              2      Phuket

In [85]:
df.iloc[[0, 1]]['name']

eid
E011      Anda
E012    Bordin
Name: name, dtype: object

In [86]:
type(df.iloc[[0, 1]]['name'])

pandas.core.series.Series

In [87]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [88]:
df.iloc[[0, 1]][['name', 'gender']]

name  gender
eid                 
E011    Anda  female
E012  Bordin    male

### Reset Index

In [89]:
df.reset_index(inplace=True)

In [90]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

### Reload Dataframe

In [91]:
df = pd.read_csv(CSV_PATH)


In [92]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

### Range Selection

In [93]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [94]:
df.loc[:4]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [95]:
df.loc[1:3, ['name','age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [96]:
df.loc[1:3][['name']]

name
1    Bordin
2  Chantana
3   Donlaya

In [97]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [98]:

df.iloc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

In [99]:
df.iloc[1:4][['name','age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

### Condition Selection

In [100]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [101]:
df[['working_years']]

working_years
0              4
1              2
2              3
3              8
4              7
5              3
6              2
7              5

In [102]:
df['working_years']

0    4
1    2
2    3
3    8
4    7
5    3
6    2
7    5
Name: working_years, dtype: int64

In [103]:
df['working_years'] > 3 # Return Boolean

0     True
1    False
2    False
3     True
4     True
5    False
6    False
7     True
Name: working_years, dtype: bool

In [104]:
df[ df['working_years'] > 3]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [105]:
df[ df['working_years'] > 3][['name','working_years','salary']]

name  working_years   salary
0     Anda              4  64200.0
3  Donlaya              8  72600.0
4  Ekkasit              7  80500.0
7    Harit              5  67700.0

In [106]:
df[ (df["working_years"]>3) & (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [107]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [108]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].iloc[[3]]

eid   name gender department  age   salary  working_years birth_place
7  E018  Harit   male     devops   32  67700.0              5     Bangkok

In [109]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].loc[[3]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

### Column Operation

In [110]:
df['salary']

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [111]:
df['salary']* 12

0    770400.0
1    584400.0
2    546000.0
3    871200.0
4    966000.0
5    679200.0
6    508800.0
7    812400.0
Name: salary, dtype: float64

In [113]:
df['salary'] * df['working_years']

0    256800.0
1     97400.0
2    136500.0
3    580800.0
4    563500.0
5    169800.0
6     84800.0
7    338500.0
dtype: float64

### New Column

In [114]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [115]:
df['country'] = 'thailand'

In [116]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country  
0  thailand  
1  thailand  
2  thailand  
3  thailand  
4  thailand  
5  thailand  
6  thailand  
7  thailand

In [117]:
df['bonus'] = df['salary'] * df['working_years']

In [118]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  thailand  256800.0  
1  thailand   97400.0  
2  thailand  136500.0  
3  thailand  580800.0  
4  thailand  563500.0  
5  thailand  169800.0  
6  thailand   84800.0  
7  thailand  338500.0

### Drop Row

In [119]:
df.drop(7)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  thailand  256800.0  
1  thailand   97400.0  
2  thailand  136500.0  
3  thailand  580800.0  
4  thailand  563500.0  
5  thailand  169800.0  
6  thailand   84800.0

In [120]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  thailand  256800.0  
1  thailand   97400.0  
2  thailand  136500.0  
3  thailand  580800.0  
4  thailand  563500.0  
5  thailand  169800.0  
6  thailand   84800.0  
7  thailand  338500.0

In [121]:
df.drop(7, inplace=True)

In [122]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  thailand  256800.0  
1  thailand   97400.0  
2  thailand  136500.0  
3  thailand  580800.0  
4  thailand  563500.0  
5  thailand  169800.0  
6  thailand   84800.0

In [123]:
df.drop([0, 1, 2])

eid     name  gender department  age   salary  working_years birth_place  \
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
3  thailand  580800.0  
4  thailand  563500.0  
5  thailand  169800.0  
6  thailand   84800.0

### Drop Column

In [128]:
df.drop('country', axis=1)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

      bonus  
0  256800.0  
1   97400.0  
2  136500.0  
3  580800.0  
4  563500.0  
5  169800.0  
6   84800.0

In [129]:
df.drop(['country', 'bonus'], axis=1)

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [131]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  thailand  256800.0  
1  thailand   97400.0  
2  thailand  136500.0  
3  thailand  580800.0  
4  thailand  563500.0  
5  thailand  169800.0  
6  thailand   84800.0

In [132]:
df.drop(['country', 'bonus'], axis=1, inplace=True)

In [133]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

### Reload the Dataframe

In [134]:
df = pd.read_csv(CSV_PATH)

In [135]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

### Sorting

In [136]:
df.sort_values('salary')

eid      name  gender department  age   salary  working_years birth_place
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
5  E016    Fundee  female    support   35  56600.0              3      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [137]:
df.sort_values(['department', 'salary'])

eid      name  gender department  age   salary  working_years birth_place
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket

In [138]:
df.sort_values('salary', ascending=False)

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [139]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [140]:
df.sort_values('salary', ascending=False, inplace=True)

In [141]:

df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [142]:

df.loc[0:2]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi

In [143]:
df.iloc[0:2]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

### Grouping

In [144]:
df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [146]:
df.groupby('department').mean()

age   salary  working_years
department                              
developer   31.0  52800.0            3.0
devops      32.0  67700.0            5.0
marketing   38.0  76550.0            7.5
support     30.5  49500.0            2.5

In [147]:
df.groupby('department').max()

eid      name gender  age   salary  working_years birth_place
department                                                                
developer   E013  Chantana   male   39  64200.0              4      Phuket
devops      E018     Harit   male   32  67700.0              5     Bangkok
marketing   E015   Ekkasit   male   39  80500.0              8  Suphanburi
support     E017   Gitiwit   male   35  56600.0              3  Suphanburi

In [148]:
df.groupby(['department', 'gender']).mean()

age   salary  working_years
department gender                              
developer  female  34.0  54850.0            3.5
           male    25.0  48700.0            2.0
devops     male    32.0  67700.0            5.0
marketing  female  39.0  72600.0            8.0
           male    37.0  80500.0            7.0
support    female  35.0  56600.0            3.0
           male    26.0  42400.0            2.0

In [150]:
df.groupby(['gender', 'department']).mean()

age   salary  working_years
gender department                              
female developer   34.0  54850.0            3.5
       marketing   39.0  72600.0            8.0
       support     35.0  56600.0            3.0
male   developer   25.0  48700.0            2.0
       devops      32.0  67700.0            5.0
       marketing   37.0  80500.0            7.0
       support     26.0  42400.0            2.0

In [151]:
df_group_obj = df.groupby('department')

In [152]:
df_group_obj

In [153]:
df_group_obj.mean()

age   salary  working_years
department                              
developer   31.0  52800.0            3.0
devops      32.0  67700.0            5.0
marketing   38.0  76550.0            7.5
support     30.5  49500.0            2.5

In [155]:
df_group_obj.max()

eid      name gender  age   salary  working_years birth_place
department                                                                
developer   E013  Chantana   male   39  64200.0              4      Phuket
devops      E018     Harit   male   32  67700.0              5     Bangkok
marketing   E015   Ekkasit   male   39  80500.0              8  Suphanburi
support     E017   Gitiwit   male   35  56600.0              3  Suphanburi

In [156]:
df.groupby('department').min()

eid     name  gender  age   salary  working_years birth_place
department                                                                
developer   E011     Anda  female   25  45500.0              2     Bangkok
devops      E018    Harit    male   32  67700.0              5     Bangkok
marketing   E014  Donlaya  female   37  72600.0              7    Chonburi
support     E016   Fundee  female   26  42400.0              2      Phuket

In [158]:

df.groupby('department').count()

eid  name  gender  age  salary  working_years  birth_place
department                                                            
developer     3     3       3    3       3              3            3
devops        1     1       1    1       1              1            1
marketing     2     2       2    2       2              2            2
support       2     2       2    2       2              2            2

In [160]:
df.groupby('department').agg({"mean", "count"})

age         salary       working_years      
            mean count     mean count          mean count
department                                               
developer   31.0     3  52800.0     3           3.0     3
devops      32.0     1  67700.0     1           5.0     1
marketing   38.0     2  76550.0     2           7.5     2
support     30.5     2  49500.0     2           2.5     2

In [162]:
df.groupby('department')['age'].agg({'mean', 'count'})

mean  count
department             
developer   31.0      3
devops      32.0      1
marketing   38.0      2
support     30.5      2

In [163]:
type(df.groupby('department')['age'].agg({'mean', 'count'}))

pandas.core.frame.DataFrame

In [164]:
df.groupby('department')[['age']].agg({'mean', 'count'})

age      
            mean count
department            
developer   31.0     3
devops      32.0     1
marketing   38.0     2
support     30.5     2

In [167]:
df.groupby("department").agg({"age":"min", "salary":"mean"})

age   salary
department              
developer    25  52800.0
devops       32  67700.0
marketing    37  76550.0
support      26  49500.0

In [166]:
df.groupby('department').agg({"age":["min","max"], "salary": "mean"})

age       salary
           min max     mean
department                 
developer   25  39  52800.0
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

In [168]:
dfg = df.groupby('department').agg({"age":["min","max"], "salary": "mean"})

In [169]:
dfg

age       salary
           min max     mean
department                 
developer   25  39  52800.0
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

In [170]:
dfg.columns

MultiIndex([(   'age',  'min'),
            (   'age',  'max'),
            ('salary', 'mean')],
           )

In [171]:
dfg[('age','min')]

department
developer    25
devops       32
marketing    37
support      26
Name: (age, min), dtype: int64

In [173]:
dfg[[('age', 'min'),('age', 'max')]]

age    
           min max
department        
developer   25  39
devops      32  32
marketing   37  39
support     26  35

In [174]:
dfg.columns

MultiIndex([(   'age',  'min'),
            (   'age',  'max'),
            ('salary', 'mean')],
           )

In [175]:
["_".join(x) for x in dfg.columns]

['age_min', 'age_max', 'salary_mean']

In [176]:
[print(x) for x in dfg.columns]

('age', 'min')
('age', 'max')
('salary', 'mean')


[None, None, None]

In [179]:
"_".join(('hello','world'))

'hello_world'

In [180]:
dfg.columns = ["_".join(x) for x in dfg.columns]

In [181]:
dfg.columns

Index(['age_min', 'age_max', 'salary_mean'], dtype='object')

In [182]:
dfg

age_min  age_max  salary_mean
department                               
developer        25       39      52800.0
devops           32       32      67700.0
marketing        37       39      76550.0
support          26       35      49500.0

In [183]:
dfg[['age_min']]

age_min
department         
developer        25
devops           32
marketing        37
support          26

In [184]:
dfg.reset_index()

department  age_min  age_max  salary_mean
0  developer       25       39      52800.0
1     devops       32       32      67700.0
2  marketing       37       39      76550.0
3    support       26       35      49500.0

In [185]:
dfg.reset_index(inplace=True)

In [186]:
dfg

department  age_min  age_max  salary_mean
0  developer       25       39      52800.0
1     devops       32       32      67700.0
2  marketing       37       39      76550.0
3    support       26       35      49500.0

### Reload dataset

In [187]:
df = pd.read_csv(CSV_PATH)

In [188]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

### Iteration

In [189]:
for index, row in df.iterrows():
	print(index)

0
1
2
3
4
5
6
7


In [190]:
for index, row in df.iterrows():
	print(row['eid'], row['name'], row['salary'])

E011 Anda 64200.0
E012 Bordin 48700.0
E013 Chantana 45500.0
E014 Donlaya 72600.0
E015 Ekkasit 80500.0
E016 Fundee 56600.0
E017 Gitiwit 42400.0
E018 Harit 67700.0


In [191]:
should_pay_ot = 'should_pay_ot'
for index, row in df.iterrows():
	#row['should_pay_ot'] = "Someting" << is not worked 
	if row['salary'] > 70000:
		df.loc[index, should_pay_ot] = 'NO'
	elif row['salary'] > 50000:
		df.loc[index, should_pay_ot] = "MAY BE"
	else:
		df.loc[index, should_pay_ot] = "YES"

In [192]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

### Reload Dataset

In [194]:
df = pd.read_csv(CSV_PATH)

In [195]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

### Apply Function

In [196]:
np.log10(1000)

3.0

In [197]:
df['salary']

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [198]:
df['salary'].apply(np.log10)

0    4.807535
1    4.687529
2    4.658011
3    4.860937
4    4.905796
5    4.752816
6    4.627366
7    4.830589
Name: salary, dtype: float64

In [199]:
df['salary'].apply(np.sqrt)

0    253.377189
1    220.680765
2    213.307290
3    269.443872
4    283.725219
5    237.907545
6    205.912603
7    260.192237
Name: salary, dtype: float64

In [200]:
def times10(num):
	return num * 10

In [201]:
times10(50)

500

In [202]:
df['age']

0    39
1    25
2    29
3    39
4    37
5    35
6    26
7    32
Name: age, dtype: int64

In [203]:
df['age'].apply(times10)

0    390
1    250
2    290
3    390
4    370
5    350
6    260
7    320
Name: age, dtype: int64

In [204]:
df['age'].apply(lambda x: x * 10)

0    390
1    250
2    290
3    390
4    370
5    350
6    260
7    320
Name: age, dtype: int64

In [205]:
def consider_ot_pay(salary):
	result = ''
	if salary > 70000:
		result = 'NO'
	elif salary > 50000:
		result = 'MAY BE'
	else:
		result = "YES"

	return result

In [206]:
consider_ot_pay(80000)

'NO'

In [207]:
consider_ot_pay(60000)

'MAY BE'

In [208]:
consider_ot_pay(30000)

'YES'

In [209]:
df['salary'].apply(consider_ot_pay)

0    MAY BE
1       YES
2       YES
3        NO
4        NO
5    MAY BE
6       YES
7    MAY BE
Name: salary, dtype: object

In [210]:
df['should_pay_ot'] = df['salary'].apply(consider_ot_pay)

In [211]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

### Save to CSV file

In [212]:
df.to_csv('employee.csv')

In [213]:
pd.read_csv('employee.csv')

Unnamed: 0   eid      name  gender department  age   salary  working_years  \
0           0  E011      Anda  female  developer   39  64200.0              4   
1           1  E012    Bordin    male  developer   25  48700.0              2   
2           2  E013  Chantana  female  developer   29  45500.0              3   
3           3  E014   Donlaya  female  marketing   39  72600.0              8   
4           4  E015   Ekkasit    male  marketing   37  80500.0              7   
5           5  E016    Fundee  female    support   35  56600.0              3   
6           6  E017   Gitiwit    male    support   26  42400.0              2   
7           7  E018     Harit    male     devops   32  67700.0              5   

  birth_place should_pay_ot  
0     Bangkok        MAY BE  
1      Phuket           YES  
2    Chonburi           YES  
3    Chonburi            NO  
4  Suphanburi            NO  
5      Phuket        MAY BE  
6  Suphanburi           YES  
7     Bangkok        MAY BE

In [214]:
df.to_csv('employee.csv', index=False)

In [215]:
pd.read_csv('employee.csv')

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

---
### Happy Ending
---